---
# 核心任务
- name: BT
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'language_selection'
      prompt: "Choose BT language \n
      1: Chinese (default)\n
      2: English\n"
      private: no
      default: 1

  vars:
     language_select:
      '1': 'zh'
      '2': 'en'

     bt_language: "{{language_select[language_selection]}}"

  roles:  

    - { role: role_cloud, tags: "role_cloud"}
    - { role: bt, tags: "bt"}
    - { role: role_common, tags: "role_common"}
    - { role: role_init, tags: "role_init", when: bt_language == 'en'}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end"}
